##################################################################
#              Docker Compose file that starts Kong              #
##################################################################

# Load Balancing
consul:
  image: progrium/consul:latest
  command: -server -bootstrap -ui-dir /ui
  restart: always
  mem_limit: 128m
  ports:
    - 8500:8500
  expose:
    - 53
    - 8300
    - 8301
    - 8302
    - 8400
    - 8500
  dns:
    - 127.0.0.1

nginx-lb:
  build: nginx/
  mem_limit: 128m
  ports:
#    - 8000:8000
    - 8443:8443
    - 8001:8001
  expose:
#    - 8000
    - 8443
    - 8001
  links:
    - consul:consul
  restart: always
  command: >
      /bin/containerpilot
      -config file:///etc/containerpilot/containerpilot.json
      nginx -g "daemon off;"

# Kong Database

kong-database:
  image: cassandra:3.11.0

  volumes:
    - /home/j/src/dbs/cassandra-kong/:/var/lib/cassandra

  ports:
    - 9042


# Gopher
gopher:
  image: blueocean/8-server-jre

  command: /usr/share/gopher-metasearcher-service/bin/gopher-metasearcher-service
  restart: always

  links:
    - dynamodb

  volumes:
    - /home/j/Desktop/docker/gopher-dev/gopher-metasearcher-service/:/usr/share/gopher-metasearcher-service

  ports:
    - 9000

# DynamoDB local
dynamodb:
  image: blueocean/8-server-jre
  working_dir: /usr/share/dynamodb
  command: java -Djava.library.path=./DynamoDBLocal_lib -jar DynamoDBLocal.jar -dbPath /usr/share/dynamodb -sharedDb
#  restart: always

  volumes:
    - /home/j/appslnx/aws/dynamodb/:/usr/share/dynamodb

  ports:
    - 8000

# Kong

kong:
  build: kong/
  restart: always
  links:
    - kong-database:kong-database
    - consul
    - gopher
  ports:
    - 8000
    - 8443
    - 8001

  expose:
    - 7946
    - 7946/udp
  environment:
    - KONG_DATABASE=cassandra
    - KONG_CASSANDRA_CONTACT_POINTS=kong-database
  
